/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VitaminRouteImport } from './routes/vitamin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrescriptionRouteImport } from './routes/prescription'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as MoodBoardRouteImport } from './routes/mood-board'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as AdminQuotesRouteImport } from './routes/admin/quotes'
import { Route as AdminPodcastsRouteImport } from './routes/admin/podcasts'
import { Route as AdminHealingRouteImport } from './routes/admin/healing'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCommunityRouteImport } from './routes/admin/community'

const VitaminRoute = VitaminRouteImport.update({
  id: '/vitamin',
  path: '/vitamin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionRoute = PrescriptionRouteImport.update({
  id: '/prescription',
  path: '/prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodBoardRoute = MoodBoardRouteImport.update({
  id: '/mood-board',
  path: '/mood-board',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/admin/quotes',
  path: '/admin/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPodcastsRoute = AdminPodcastsRouteImport.update({
  id: '/admin/podcasts',
  path: '/admin/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHealingRoute = AdminHealingRouteImport.update({
  id: '/admin/healing',
  path: '/admin/healing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/admin/community',
  path: '/admin/community',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/mood': typeof MoodRoute
  '/mood-board': typeof MoodBoardRoute
  '/podcast': typeof PodcastRoute
  '/prescription': typeof PrescriptionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vitamin': typeof VitaminRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/healing': typeof AdminHealingRoute
  '/admin/podcasts': typeof AdminPodcastsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/u/$userId': typeof UUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/mood': typeof MoodRoute
  '/mood-board': typeof MoodBoardRoute
  '/podcast': typeof PodcastRoute
  '/prescription': typeof PrescriptionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vitamin': typeof VitaminRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/healing': typeof AdminHealingRoute
  '/admin/podcasts': typeof AdminPodcastsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/u/$userId': typeof UUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/mood': typeof MoodRoute
  '/mood-board': typeof MoodBoardRoute
  '/podcast': typeof PodcastRoute
  '/prescription': typeof PrescriptionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vitamin': typeof VitaminRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/healing': typeof AdminHealingRoute
  '/admin/podcasts': typeof AdminPodcastsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/u/$userId': typeof UUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/journal'
    | '/mood'
    | '/mood-board'
    | '/podcast'
    | '/prescription'
    | '/reset-password'
    | '/vitamin'
    | '/admin/community'
    | '/admin/dashboard'
    | '/admin/healing'
    | '/admin/podcasts'
    | '/admin/quotes'
    | '/u/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/journal'
    | '/mood'
    | '/mood-board'
    | '/podcast'
    | '/prescription'
    | '/reset-password'
    | '/vitamin'
    | '/admin/community'
    | '/admin/dashboard'
    | '/admin/healing'
    | '/admin/podcasts'
    | '/admin/quotes'
    | '/u/$userId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/journal'
    | '/mood'
    | '/mood-board'
    | '/podcast'
    | '/prescription'
    | '/reset-password'
    | '/vitamin'
    | '/admin/community'
    | '/admin/dashboard'
    | '/admin/healing'
    | '/admin/podcasts'
    | '/admin/quotes'
    | '/u/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  JournalRoute: typeof JournalRoute
  MoodRoute: typeof MoodRoute
  MoodBoardRoute: typeof MoodBoardRoute
  PodcastRoute: typeof PodcastRoute
  PrescriptionRoute: typeof PrescriptionRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VitaminRoute: typeof VitaminRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminHealingRoute: typeof AdminHealingRoute
  AdminPodcastsRoute: typeof AdminPodcastsRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  UUserIdRoute: typeof UUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vitamin': {
      id: '/vitamin'
      path: '/vitamin'
      fullPath: '/vitamin'
      preLoaderRoute: typeof VitaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription': {
      id: '/prescription'
      path: '/prescription'
      fullPath: '/prescription'
      preLoaderRoute: typeof PrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood-board': {
      id: '/mood-board'
      path: '/mood-board'
      fullPath: '/mood-board'
      preLoaderRoute: typeof MoodBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/admin/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/podcasts': {
      id: '/admin/podcasts'
      path: '/admin/podcasts'
      fullPath: '/admin/podcasts'
      preLoaderRoute: typeof AdminPodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/healing': {
      id: '/admin/healing'
      path: '/admin/healing'
      fullPath: '/admin/healing'
      preLoaderRoute: typeof AdminHealingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/community': {
      id: '/admin/community'
      path: '/admin/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  JournalRoute: JournalRoute,
  MoodRoute: MoodRoute,
  MoodBoardRoute: MoodBoardRoute,
  PodcastRoute: PodcastRoute,
  PrescriptionRoute: PrescriptionRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VitaminRoute: VitaminRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminHealingRoute: AdminHealingRoute,
  AdminPodcastsRoute: AdminPodcastsRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  UUserIdRoute: UUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
