/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VitaminRouteImport } from './routes/vitamin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'

const VitaminRoute = VitaminRouteImport.update({
  id: '/vitamin',
  path: '/vitamin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/mood': typeof MoodRoute
  '/podcast': typeof PodcastRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vitamin': typeof VitaminRoute
  '/admin/dashboard': typeof AdminDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/mood': typeof MoodRoute
  '/podcast': typeof PodcastRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vitamin': typeof VitaminRoute
  '/admin/dashboard': typeof AdminDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/mood': typeof MoodRoute
  '/podcast': typeof PodcastRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vitamin': typeof VitaminRoute
  '/admin/dashboard': typeof AdminDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/journal'
    | '/mood'
    | '/podcast'
    | '/reset-password'
    | '/vitamin'
    | '/admin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/journal'
    | '/mood'
    | '/podcast'
    | '/reset-password'
    | '/vitamin'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/journal'
    | '/mood'
    | '/podcast'
    | '/reset-password'
    | '/vitamin'
    | '/admin/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  JournalRoute: typeof JournalRoute
  MoodRoute: typeof MoodRoute
  PodcastRoute: typeof PodcastRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VitaminRoute: typeof VitaminRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vitamin': {
      id: '/vitamin'
      path: '/vitamin'
      fullPath: '/vitamin'
      preLoaderRoute: typeof VitaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  JournalRoute: JournalRoute,
  MoodRoute: MoodRoute,
  PodcastRoute: PodcastRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VitaminRoute: VitaminRoute,
  AdminDashboardRoute: AdminDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
